name: flash_stick_notes
description: A modern stick note.
version: 0.0.1
publish_to: "none"
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get: ^4.6.5
  get_storage: ^2.1.1
  uuid: ^3.0.5
  drift: ^2.8.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.3
  http: ^0.13.0
  launch_at_startup: ^0.2.2
  package_info_plus: ^4.0.2
  bot_toast: ^4.0.3
  fluentui_system_icons: ^1.1.203
  file_picker: ^5.2.2
  pasteboard: ^0.2.0
  hotkey_manager: ^0.1.7
  window_manager: ^0.3.5
  tray_manager: ^0.2.0
  intl: ^0.18.0
  drift_db_viewer: ^2.0.0
  rxdart: ^0.27.7
  flutter_quill:
    git:
      url: https://github.com/TheHeBoy/flutter-quill.git
      ref: 1.0.0.0
  flutter_quill_extensions:
    git:
      url: https://github.com/TheHeBoy/flutter-quill.git
      path: flutter_quill_extensions
      ref: 1.0.0.0

dependency_overrides:
#  flutter_quill:
#    path: package/flutter-quill
#  flutter_quill_extensions:
#    path: package/flutter-quill/flutter_quill_extensions
  flutter_quill:
    git:
      url: https://github.com/TheHeBoy/flutter-quill.git
      ref: 1.0.0.0
  flutter_quill_extensions:
    git:
      url: https://github.com/TheHeBoy/flutter-quill.git
      path: flutter_quill_extensions
      ref: 1.0.0.0

dev_dependencies:
  drift_dev: ^2.8.2
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: MiSans
      fonts:
        - asset: assets/fonts/MiSans-Regular.ttf
        - asset: assets/fonts/MiSans-Semibold.ttf
          weight: 600
        - asset: assets/fonts/MiSans-Bold.ttf
          weight: 700
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf